### ISSUE TITLE
Upgrade to latest prebid.js version

### ISSUE THREAD

**Issue by elbidone** [meumobi/ams-hb#24]
[Prebid 1.0 Publisher API Changes](http://prebid.org/dev-docs//prebid-1.0-API.html)
incl. same adapters as previous version, but remove piximedia and add [consentManagement](http://prebid.org/dev-docs/modules/consentManagement.html)

**Comment by danconte72** [comment]
the is no Criteo module so far

**Comment by danconte72** [comment]
Checking all API changes we just have to remove pbams.setPriceGranularity('dense'); 
Replacing by pbams.setConfig({ priceGranularity: 'dense' });

**Comment by danconte72** [comment]
[Criteo PR ](https://github.com/prebid/Prebid.js/pull/2370)

**Comment by elbidone** [comment]
bidders are not launched, I'm not sure you are following v1.x specifications, please check [AdUnit reference](http://prebid.org/dev-docs/adunit-reference.html).
