### ISSUE TITLE
Calls to adserver are not made when no bidders responded

### ISSUE THREAD

**Issue by elbidone** [meumobi/ams-hb#28]

**Comment by elbidone** [comment]
![image](https://user-images.githubusercontent.com/9011612/43901886-845a5dbc-9be0-11e8-8942-9c0ac1bf0fc5.png)
when bidder responded, everything works as it should :
![image 1](https://user-images.githubusercontent.com/9011612/43901885-843aa800-9be0-11e8-88cd-9f68303c8cc0.png)
If  I use "?pbjs_debug=true", this error pops :
![image 2](https://user-images.githubusercontent.com/9011612/43901884-8416dcea-9be0-11e8-9c4e-4ba37f676bc3.png)

**Comment by danconte72** [comment]
When there is no bid responses, the targeting params are empty

This error showed up when updated the prebid.js from 1.13 to 1.14.
I've tested the latest prebid.js 1.19 and the error persists;

**Comment by danconte72** [comment]
the current check is useless in latest versions
```js
if (targetingParams.hasOwnProperty(slot)) {
 ...
}
```

**Comment by elbidone** [comment]
ok, then we should keep prebidams 1.14 and and update our code for the latest format of tragetParams to prevent errors ?
